import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Use | EduScribe',
  description: 'Terms of Use for EduScribe - AI-powered educational content generator'
}

export default function TermsOfUse() {
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-8">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-6">
            Terms of Use – EduScribe
          </h1>
          
          <p className="text-gray-600 dark:text-gray-300 mb-8">
            <strong>Effective Date:</strong> January 1, 2024
          </p>

          <div className="prose prose-gray dark:prose-invert max-w-none">
            <ol className="space-y-6 text-gray-700 dark:text-gray-300">
              <li>
                <strong className="text-gray-900 dark:text-white text-lg">Acceptance of Terms</strong>
                <p className="mt-2">
                  By using the EduScribe service ("Service"), you confirm that you are at least 13 years old 
                  and agree to be bound by these Terms of Use. If you are under 18, you must have parental 
                  or guardian consent to use our Service.
                </p>
              </li>

              <li>
                <strong className="text-gray-900 dark:text-white text-lg">Description of Service</strong>
                <p className="mt-2">
                  EduScribe provides users with tools to generate educational content from various sources 
                  including YouTube videos, uploaded files, and text input. Our AI-powered platform creates 
                  notes, summaries, and educational materials to support learning and teaching activities.
                </p>
              </li>

              <li>
                <strong className="text-gray-900 dark:text-white text-lg">Accounts and Subscriptions</strong>
                <p className="mt-2">
                  You are responsible for maintaining the confidentiality of your account credentials and 
                  for all activities that occur under your account. We offer various subscription plans 
                  with different usage limits and features. Subscription fees are charged according to 
                  your selected plan.
                </p>
              </li>

              <li>
                <strong className="text-gray-900 dark:text-white text-lg">No Guarantee of Uninterrupted Service</strong>
                <p className="mt-2">
                  We aim to keep EduScribe operational at all times, but we cannot guarantee 100% uptime. 
                  The Service may be temporarily unavailable due to maintenance, updates, or technical issues. 
                  We are not liable for any inconvenience or loss resulting from service interruptions.
                </p>
              </li>

              <li>
                <strong className="text-gray-900 dark:text-white text-lg">No Refunds</strong>
                <p className="mt-2">
                  EduScribe is provided "as-is" and "as available." We do not offer refunds for subscription 
                  fees, unused credits, or any other charges unless required by applicable law. All sales 
                  are final. You may cancel your subscription at any time to prevent future charges.
                </p>
              </li>

              <li>
                <strong className="text-gray-900 dark:text-white text-lg">User-Generated Content</strong>
                <p className="mt-2">
                  You are solely responsible for any content you upload, input, or generate using our Service. 
                  You warrant that you have the necessary rights to use such content and that it does not 
                  violate any third-party rights or applicable laws. We reserve the right to remove content 
                  that violates these terms.
                </p>
              </li>

              <li>
                <strong className="text-gray-900 dark:text-white text-lg">Intellectual Property</strong>
                <p className="mt-2">
                  All content, design, and code on EduScribe is the property of EduScribe or its licensors. 
                  The content generated by our AI tools based on your input is provided to you for your 
                  educational use. You retain rights to your original input content.
                </p>
              </li>

              <li>
                <strong className="text-gray-900 dark:text-white text-lg">Modifications to Terms</strong>
                <p className="mt-2">
                  We may update these Terms from time to time. We will notify users of significant changes 
                  via email or through the Service. Continued use of the Service after changes constitutes 
                  acceptance of the updated Terms.
                </p>
              </li>

              <li>
                <strong className="text-gray-900 dark:text-white text-lg">Termination</strong>
                <p className="mt-2">
                  We reserve the right to suspend or terminate your access to the Service at any time for 
                  violation of these Terms or for any other reason at our sole discretion. You may terminate 
                  your account at any time by contacting us or through account settings.
                </p>
              </li>

              <li>
                <strong className="text-gray-900 dark:text-white text-lg">Limitation of Liability</strong>
                <p className="mt-2">
                  To the fullest extent permitted by law, EduScribe shall not be liable for any indirect, 
                  incidental, special, or consequential damages arising from your use of the Service. 
                  Our total liability shall not exceed the amount paid by you for the Service in the 
                  twelve months preceding the claim.
                </p>
              </li>

              <li>
                <strong className="text-gray-900 dark:text-white text-lg">Governing Law</strong>
                <p className="mt-2">
                  These Terms shall be governed by the laws of Poland, without regard to conflict of law 
                  provisions. Any disputes arising from these Terms or the Service shall be resolved in 
                  the courts of Poland.
                </p>
              </li>

              <li>
                <strong className="text-gray-900 dark:text-white text-lg">Contact</strong>
                <p className="mt-2">
                  For any questions or concerns regarding these Terms of Use, please contact us at:{' '}
                  <a 
                    href="mailto:support@eduscribe.com" 
                    className="text-blue-600 dark:text-blue-400 hover:underline"
                  >
                    support@eduscribe.com
                  </a>
                </p>
              </li>
            </ol>
          </div>

          <div className="mt-8 pt-6 border-t border-gray-200 dark:border-gray-700">
            <p className="text-sm text-gray-500 dark:text-gray-400 text-center">
              Last updated: January 1, 2024
            </p>
          </div>
        </div>
      </div>
    </div>
  )
} 